Transform to ES5
poppinss/indicative pull request #194
Opened 2018-06-17 08:06 UTC by mhemrg

Closes #177 
Related to https://github.com/Slynova-Org/charmap/pull/4

2018-06-18 04:49 UTC, thetutlage requested changes

2018-06-18 04:49 UTC, thetutlage commented on package.json
> +    "striptags": "^2.2.1",
May I know why we decreased the version of `striptags`?

2018-06-18 06:25 UTC, mhemrg commented on package.json
> +    "striptags": "^2.2.1",
According to its docs, `v3+` targets ES6 and is incompatible with `uglifyjs`.

2018-06-18 11:33 UTC, thetutlage commented on package.json
> +    "striptags": "^2.2.1",
Yeah will be better, if you can add a proper reasoning behind these random changes.

2018-06-18 11:39 UTC, thetutlage commented
Can you share some steps on how do I verify that it is compatible with ES5?

2018-06-18 12:44 UTC, mhemrg commented
In order to transpile indicative to ES5, we have to have transpiled dependencies. I've decreased the version of `striptags` to 2 because it targets ES5. I've upgraded `@slynova/slug` and `haye` too because they're compatible with ES5 in they're latest versions.

We're using `uglify-es`, but if we use `uglifyjs` it will break. `uglifyjs` requires ES5 compatibility.

2018-06-23 00:36 UTC, 7ammer commented
This saved my bacon. Thanks!

2018-07-18 12:47 UTC, closed without merging